server:
  port: 5008

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**, /api/admin/users/**, /api/users/**, /users/**
            - id: SALON-SERVICE
              uri: lb://SALON-SERVICE
              predicates:
                - Path=/salons/**, /api/admin/salons/**, /api/salons/**
            - id: BOOKING-SERVICE
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path= /api/bookings/**
            - id: SERVICE-OFFERING
              uri: lb://SERVICE-OFFERING
              predicates:
                - Path= /api/service-offering/**
            - id: PAYMENT-SERVICE
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path= /api/payments/**
            - id: CATEGORY-SERVICE
              uri: lb://CATEGORY-SERVICE
              predicates:
                - Path= /api/categories/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"