server:
  port: 5006

spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/paymentDB_salon?createDatabaseIfNotExist=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver



razorpay:
  api:
    key: "your razor pay api secret"
    secret: "your razor pay api secret"

stripe:
  api:
    key: "your stripe pay api key"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"